# Generated by Django 4.1 on 2022-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='releas_date',
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
