# Generated by Django 4.1 on 2022-09-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_releas_date_phone_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
