# Generated by Django 4.1 on 2022-09-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_phone_lte_exists_alter_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(),
        ),
    ]
